resources:
  - ../../../base

namespace: production
namePrefix: puppeteer-production-

commonLabels:
  app: puppeteer-production

images:
  - name: registry.digitalocean.com/sohnandsol/puppeteer-production
    newTag: v1.0.0

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: auth
        namespace: placeholder
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: in
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0/targetPort
        value: 4000
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.digitalocean.com/sohnandsol/puppeteer-production:v1.0.0
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: puppeteer-production        
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 4000
