apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digitalocean
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: envs/digitalocean/argocd
    targetRevision: main
    repoURL: https://github.com/Breldan-Muturi/nx-kippra.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
