version: '3.8'
services:
  portal:
    image: breldan/nx-kippraportal
    build:
      context: .
      dockerfile: apps/portal/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
  puppeteer:
    image: breldan/nx-kipprapuppeteer
    build:
      context: .
      dockerfile: apps/puppeteer/Dockerfile
    ports:
      - 3333:3333
