apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: production-pg
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  bootstrap:
    initdb:
      database: production
      owner: app
      secret:
        name: production-app-user
  superuserSecret:
    name: production-superuser
  storage:
    size: 5Gi
    storageClass: do-block-storage
