apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: staging-postgres
  namespace: postgres
spec:
  description: 'staging db'
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  instances: 1
  startDelay: 10
  stopDelay: 10
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: staging
      owner: app
      secret:
        name: staging-app-user
  superuserSecret:
    name: staging-superuser
  storage:
    size: 3Gi
    storageClass: do-block-storage
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1
