apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-databases
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: staging
          - name: production
  template:
    metadata:
      name: '{{name}}-postgres'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: postgresql
        targetRevision: 15.5.14
        helm:
          values: |
            global:
              postgresql:
                auth:
                  existingSecret: postgres-{{name}}-auth
                  secretKeys:
                    userPasswordKey: password
                    adminPasswordKey: postgres-password
                  username: '{{name}}-admin'
                  database: "{{name}}"
                  enablePostgresUser: true
            primary:
              persistence:
                enabled: true
                size: 5Gi
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
