name: Build and Push Docker Image
on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true
      resend:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Create .env fiile
        run: |
          echo "NEXT_PUBLIC_RESEND_API_KEY=${{ secrets.resend}}" > .env

      - name: Build and Push Docker Image using Docker Compose
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f compose.yml build --no-cache
          docker compose -f compose.yml push
