name: Build and Deploy Project
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: contains(github.event.head_commit.modified_files, 'nginx.conf')
    uses: ./.github/workflows/build-and-push.yml
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      resend: ${{ secrets.NEXT_PUBLIC_RESEND_API_KEY}}

  deploy-to-droplet:
    needs: build-and-push
    if: contains(github.event.head_commit.modified_files, 'nginx.conf')
    uses: ./.github/workflows/deploy-to-droplet.yml
    secrets:
      host: ${{ secrets.DROPLET_SSH_HOST }}
      username: ${{ secrets.DROPLET_SSH_USERNAME }}
      password: ${{ secrets.DROPLET_SSH_PASSWORD }}
      port: ${{ secrets.DROPLET_SSH_PORT }}

  updates-nginx:
    # needs: deploy-to-droplet
    if: contains(github.event.head_commit.modified, 'nginx.conf')
    uses: ./.github/workflows/update-nginx.yml
    secrets:
      host: ${{ secrets.DROPLET_SSH_HOST }}
      username: ${{ secrets.DROPLET_SSH_USERNAME }}
      password: ${{ secrets.DROPLET_SSH_PASSWORD }}
      port: ${{ secrets.DROPLET_SSH_PORT }}
