name: Update Nginx
on:
  workflow_call:
    secrets:
      host:
        required: true
      username:
        required: true
      password:
        required: true
      port:
        required: true

jobs:
  updates-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -al

      - name: Copy Nginx Configuration to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          source: 'nginx.conf'
          target: '/etc/nginx/sites-available'
          timeout: '180s'
          command_timeout: '120s'
          rm: true

      - name: Test and Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          script: |
            set -e
            echo "Testing nginx configuration"
            sudo nginx -t
            echo "Restarting nginx"
            sudo systemctl restart nginx
