name: Update Nginx
on:
  workflow_call:
    secrets:
      host:
        required: true
      username:
        required: true
      password:
        required: true
      port:
        required: true

jobs:
  updates-nginx:
    runs-on: ubuntu-latest
    steps:
      = name: List repository files
        uses: ls -al
        
      - name: Copy Nginx Configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          script: |
            set e
            echo "Copying nginx.conf to /etc/nginx/sites-available/nx-portal"
            sudo cp ./nginx.conf /etc/nginx/sites-available/nx-portal
            echo "Testing nginx configuration"
            sudo nginx -t
            echo "Restarting nginx"
            sudo systemctl restart nginx
